#!/bin/bash

# get the directory of this script so we can execute the related python
# This part is borrowed from Facebook Path Picker (https://github.com/facebook/PathPicker/)
SOURCE=$0
# resolve $SOURCE until the file is no longer a symlink
while [ -h "$SOURCE" ]; do
  BASEDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  # if $SOURCE was a relative symlink, we need to resolve it relative to
  # the path where the symlink file was located
  [[ $SOURCE != /* ]] && SOURCE="$BASEDIR/$SOURCE"
done
BASEDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

PYTHONCMD="python"
RELATIVEPATHS=0

function doProgram {
  # run main python script
  $PYTHONCMD "$BASEDIR/src/main.py" "$@"
}
while [[ $# > 0 ]]
do
opt="$1"

case $opt in 
    -h|--help)
    $PYTHONCMD "$BASEDIR/src/printHelp.py"
    exit 0
    ;;
    --debug)
    echo "Executing from '$BASEDIR'"
    ;;
    --version)
    VERSION="$($PYTHONCMD "$BASEDIR/src/version.py")"
    echo "pj version $VERSION"
    exit 0
    ;;
    --python3)
    PYTHONCMD="python3"
    ;;
    -f|--filter) 
    FILTER="$2"
    shift
    ;;
    -r|--relative-path) 
    RELATIVEPATH=1
    ;;
    *)
    ;;
esac
shift
done

doProgram "$FILTER" "$RELATIVEPATH"
